

GET http://localhost:8080/contacts
# the request above returns a json object with all contact information from data


###Single requests

GET http://localhost:8080/contacts/633b860bf1ca7e3a1f473ae6



###
 https://cse-341-week2.onrender.com/contacts

###
 https://cse-341-week2.onrender.com/contacts/633b860bf1ca7e3a1f473ae6
